// error catcher function

const errCatcher = (err) => console.log(err);

module.exports = errCatcher;